[package]
name = "weatherstation"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
anyhow = "1"
#rtlsdr_mt = "2"
chrono = "0.4"
bitvec = "0.22"
crc-any = "2"
