version: '3.4'

services:
  weatherradio:
    build: .
    restart: unless-stopped
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/root/.config/weatherradio
